---
- name: restart tomcat
  service:
    name: tomcat9
    state: restarted

- name: restart apache
  service:
    name: apache2
    state: restarted

- name: rebuild war file
  shell: "JAVA_HOME=/usr ./bin/build.sh -Didp.target.dir=/opt/shibboleth-idp"
  args:
    chdir: "/opt/shibboleth-idp"

- name: reload instance
  file:
    path: "/opt/shibboleth-idp/war/idp.war"
    state: touch
