---
- name: install packages
  apt:
    name: ['apache2']
    state: present

- name: make sure apache is running
  service:
    name: apache2
    state: restarted

- name: load apache modules
  apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    # for sync and share SPs coming in via ECP
    - authnz_ldap
    - authz_groupfile
    - headers
    - proxy
    - proxy_ajp
    - rewrite
    - ssl
  notify: restart apache

- name: configure ports
  template:
    src: templates/etc/apache2/ports.conf.j2
    dest: /etc/apache2/ports.conf
    owner: root
    group: root
    mode: 0644

- name: configure SSL
  blockinfile:
    path: /etc/apache2/mods-enabled/ssl.conf
    insertbefore: "</IfModule>"
    block: "{{
      lookup('file', 'templates/block-mozilla-ssl-config-generator.j2')
    }}"

- name: ensure that the directories for ssl certs are present
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - /etc/ssl/aai
    - /etc/ssl/localcerts
