---
repos:
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v6.0.2
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        args:
          - "--progressive"

  - repo: https://github.com/thibaudcolas/curlylint
    rev: "v0.13.1" # select a tag / sha to point at
    hooks:
      - id: curlylint
        files: \.(j2)$
