---
### conf/access-control.xml ###
- name: configure access to IdP webservices
  lineinfile:
    path: /opt/shibboleth-idp/conf/access-control.xml
    regexp: "p:allowedRanges"
    line: p:allowedRanges="#{ {'127.0.0.1/32', '::1/128', '{{ statuspage_ipv4 }}', '{{ statuspage_ipv6 }}'} }" />
    insertafter: '<bean parent="shibboleth.IPRangeAccessControl"'

- name: configure access to status page for own and DFN monitoring IP ranges
  blockinfile:
    path: /opt/shibboleth-idp/conf/access-control.xml
    block: |
      <entry key="StatusAccessByIPAddress">
          <bean parent="shibboleth.IPRangeAccessControl" p:allowedRanges="#{ {'127.0.0.1/32', '::1/128', '{{ statuspage_ipv4 }}', '{{ statuspage_ipv6 }}', '193.174.247.0/24', '2001:638:206:1::/64'} }" />
      </entry>
    insertbefore: "</util:map>"
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"

- name: add reference to access policy in idp.properties
  lineinfile:
    path: /opt/shibboleth-idp/conf/idp.properties
    line: idp.status.accessPolicy=StatusAccessByIPAddress
