---
dependency:
  name: galaxy
  options:
    role-file: ../../requirements.yml
    requirements-file: ../../requirements.yml

driver:
  name: docker

platforms:

  - name: debian11
    image: geerlingguy/docker-debian11-ansible
    pre_build_image: true
  - name: ubuntu2004
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    pre_build_image: true

provisioner:
  name: ansible

verifier:
  name: ansible
