---
- name: restart tomcat
  ansible.builtin.service:
    name: tomcat10
    state: restarted

- name: restart apache
  ansible.builtin.service:
    name: apache2
    state: restarted

- name: rebuild war file
  environment:
    JAVA_HOME: "/usr"
  ansible.builtin.command:
    argv:
      - "./bin/build.sh"
      - "-Didp.target.dir=/opt/shibboleth-idp"
    chdir: "/opt/shibboleth-idp"

- name: reload instance
  ansible.builtin.file:
    path: "/opt/shibboleth-idp/war/idp.war"
    state: touch
    owner: root
    group: root
    mode: 0644
