---
- name: restart tomcat
  service:
    name: tomcat9
    state: restarted

- name: restart apache
  service:
    name: apache2
    state: restarted

- name: rebuild war file
  environment:
    JAVA_HOME: "/usr"
  command:
    argv:
      - "./bin/build.sh"
      - "-Didp.target.dir=/opt/shibboleth-idp"
    chdir: "/opt/shibboleth-idp"

- name: reload instance
  file:
    path: "/opt/shibboleth-idp/war/idp.war"
    state: touch
    owner: root
    group: root
    mode: 0644
