---
mdq_checksum: >-
  sha256:24f9f5744f7e326fa571caba4ad4ea87ce97dd2c61e93514feb63576732b3877

idp_installation_script: "{{
      '/opt/install/shibboleth-identity-provider-' +
      shibboleth_idp_version +
      '/bin/install.sh'
}}"
idp_src_dir: "{{
      '/opt/install/shibboleth-identity-provider-' +
      shibboleth_idp_version
}}"

idp_ansible_indicator: >-
    /opt/shibboleth-idp/.ansible_initial_installation_successful.log

statuspage_dfn_ipv4: "193.174.247.0/24"
statuspage_dfn_ipv6: "2001:638:206:1::/64"

idp_archive_url: "{{
  'https://shibboleth.net/downloads/identity-provider/' +
  'archive/' +
  shibboleth_idp_version +
  '/shibboleth-identity-provider-' +
  shibboleth_idp_version +
  '.tar.gz'
}}"

idp_archive_checksum_url: "{{
  'https://shibboleth.net/downloads/identity-provider/' +
  shibboleth_idp_version +
  '/shibboleth-identity-provider-' +
  shibboleth_idp_version +
  '.tar.gz.asc'
}}"

idp_keys_url: "{{
  'https://shibboleth.net/downloads/PGP_KEYS'
}}"


# certificate basename depends on hostname to support multiple hosts
idp_webserver_basename: "{{ idp_fqdn }}_{{ inventory_hostname }}"
idp_webserver_privatekey: "{{
  '/etc/ssl/private/' +
  idp_webserver_basename +
  '.key.pem'
}}"
idp_webserver_certificate: "{{
  '/etc/ssl/localcerts/' +
  idp_webserver_basename +
  '.crt.pem'
}}"
idp_webserver_signing_request: "{{
  '/etc/ssl/csr/' +
  idp_webserver_basename +
  '.csr'
}}"
idp_webserver_fullchain: "{{
  '/etc/ssl/localcerts/' +
  idp_webserver_basename +
  '_completechain.crt.pem'
}}"

# TODO Check how this should be handled in federating system
idp_saml_privatekey: "/etc/ssl/private/{{ idp_fqdn }}-saml.key.pem"
idp_saml_certificate: "/etc/ssl/localcerts/{{ idp_fqdn }}-saml.crt.pem"
idp_saml_signing_request: "/etc/ssl/csr/{{ idp_fqdn }}-saml.csr"

idp_xml_namespaces:
  beans: "http://www.springframework.org/schema/beans"
  util: "http://www.springframework.org/schema/util"
  context: "http://www.springframework.org/schema/context"
  p: "http://www.springframework.org/schema/p"
  c: "http://www.springframework.org/schema/c"
  xsi: "http://www.w3.org/2001/XMLSchema-instance"

idp_access_policies_xpath: "/beans:beans/util:map[@id='shibboleth.AccessControlPolicies']"
idp_access_policies_entry_xpath: "{{ idp_access_policies_xpath }}/beans:entry"

idp_intercept_policies_xpath: "/beans:beans/util:map[@id='shibboleth.AccessControlPolicies']"
