---
mdq_checksum: >-
  sha256:24f9f5744f7e326fa571caba4ad4ea87ce97dd2c61e93514feb63576732b3877

idp_installation_script: "{{
      '/opt/install/shibboleth-identity-provider-' +
      shibboleth_idp_version +
      '/bin/install.sh'
}}"
idp_src_dir: "{{
      '/opt/install/shibboleth-identity-provider-' +
      shibboleth_idp_version
}}"

idp_ansible_indicator: >-
    /opt/shibboleth-idp/.ansible_initial_installation_successful.log

statuspage_dfn_ipv4:
  - 193.174.247.0/24
  - 194.95.243.0/24
  - 194.95.244.0/24
  - 194.95.242.0/24

statuspage_dfn_ipv6:
  - 2001:638:206:1::/64

idp_archive_url: "{{
  'https://shibboleth.net/downloads/identity-provider/' +
  'archive/' +
  shibboleth_idp_version +
  '/shibboleth-identity-provider-' +
  shibboleth_idp_version +
  '.tar.gz'
}}"

idp_archive_checksum_url: "{{
  'https://shibboleth.net/downloads/identity-provider/' +
  shibboleth_idp_version +
  '/shibboleth-identity-provider-' +
  shibboleth_idp_version +
  '.tar.gz.asc'
}}"

idp_keys_url: "{{
  'https://shibboleth.net/downloads/PGP_KEYS'
}}"

jdbc_plugin_archive_url: "{{
  'https://shibboleth.net/downloads/identity-provider/plugins/jdbc/' +
  jdbc_plugin_version +
  '/java-plugin-jdbc-storage-' +
  jdbc_plugin_version +
  '.tar.gz'
}}"

jdbc_plugin_signature_url: "{{
  'https://shibboleth.net/downloads/identity-provider/plugins/jdbc/' +
  jdbc_plugin_version +
  '/java-plugin-jdbc-storage-' +
  jdbc_plugin_version +
  '.tar.gz.asc'
}}"