---
- name: install required packages
  ansible.builtin.apt:
    name: ['systemd-timesyncd', 'openjdk-11-jdk-headless', 'tomcat9', 'libtaglibs-standard-impl-java']
    state: present

- name: give tomcat enough memory
  ansible.builtin.lineinfile:
    path: /etc/default/tomcat9
    regexp: '^JAVA_OPTS'
    line: 'JAVA_OPTS="-Djava.awt.headless=true -XX:+UseConcMarkSweepGC -Xms1024m -Xmx2048m"'

- name: make sure the ssl-cert group exists
  ansible.builtin.group:
    name: ssl-cert
    state: present

- name: add tomcat user to ssl-cert group
  ansible.builtin.user:
    name: tomcat
    groups: ssl-cert
    append: true

# Systemd override configuration so that tomcat can write logs and metadata.
# The target directories have to exist before the override is created.
- name: add systemd subdirectory
  ansible.builtin.file:
    path: /etc/systemd/system/tomcat9.service.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create /opt/shibboleth-idp/metadata directory
  ansible.builtin.file:
    path: /opt/shibboleth-idp/metadata
    state: directory
    recurse: true
    owner: tomcat
    group: tomcat
    mode: 0755

- name: Create /opt/shibboleth-idp/logs directory
  ansible.builtin.file:
    path: /opt/shibboleth-idp/logs
    state: directory
    owner: tomcat
    group: tomcat
    mode: 0755

- name: make logs and metadata directories read-writeable
  ansible.builtin.blockinfile:
    path: /etc/systemd/system/tomcat9.service.d/override.conf
    create: true
    block: |
      [Service]
      ReadWritePaths=/opt/shibboleth-idp/logs
      ReadWritePaths=/opt/shibboleth-idp/metadata
    owner: root
    group: root
    mode: 0644
  notify: daemon-reload

- name: template for /etc/tomcat9/server.xml
  ansible.builtin.template:
    src: templates/etc/tomcat9/server.xml.j2
    dest: /etc/tomcat9/server.xml
    owner: root
    group: tomcat
    mode: 0640

- name: disable session persistence across tomcat restarts
  ansible.builtin.blockinfile:
    path: /etc/tomcat9/context.xml
    block: |
      <!-- Uncomment this to disable session persistence across Tomcat restarts -->
      <Manager pathname="" />
    insertbefore: '^</Context>'

- name: append path to JSTL path to common loader
  ansible.builtin.lineinfile:
    path: /etc/tomcat9/catalina.properties
    regexp: '^common.loader='
    line: 'common.loader="${catalina.base}/lib","${catalina.base}/lib/*.jar","${catalina.home}/lib","${catalina.home}/lib/*.jar","/usr/share/java/*.jar"'

- name: prepare configuration for IdP servlet
  ansible.builtin.template:
    src: templates/etc/tomcat9/Catalina/localhost/idp.xml.j2
    dest: /etc/tomcat9/Catalina/localhost/idp.xml
    owner: root
    group: tomcat
    mode: 0644
