---
- name: manage private key
  block:

    - name: copy private key to webserver
      ansible.builtin.copy:
        src: "{{ idp_webserver_privatekey | basename }}"
        dest: "{{ idp_webserver_privatekey }}"
        owner: root
        group: ssl-cert
        mode: 0640

    - name: validate private key
      openssl_privatekey_info:
        path: "{{ idp_webserver_privatekey }}"

  rescue:

    - name: inform user on private key problem
      pause:
        prompt: |
          There was a problem deploying your provided private key.
          Either it was not provided as

            {{ idp_webserver_privatekey | basename }}

          or it was invalid.
      failed_when: true

- name: manage certificate
  block:

    - name: DFN-PKI certificate for webserver
      copy:
        src: "{{ idp_webserver_certificate | basename }}"
        dest: "{{ idp_webserver_certificate }}"
        owner: root
        group: ssl-cert
        mode: 0644

    - name: validate DFN-PKI certificate for webserver
      community.crypto.x509_certificate_info:
        path: "{{ idp_webserver_certificate }}"

  rescue:

    - name: inform user on certificate problem
      pause:
        prompt: |
          There was a problem deploying your provided certificate.
          Either it was not provided as

            {{ idp_webserver_certificate | basename }}

          or it was invalid.
      failed_when: true
