---
# Here the cert/key pair is checked.
- name: openssl certificate management
  block:

    - name: ensure that the directories for ssl certs are present
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      loop:
        - /etc/ssl/localcerts

    - name: check presence and permissions of private key
      block:

        - name: private key for webserver certificate
          ansible.builtin.file:
            path: "{{ idp_webserver_privatekey }}"
            state: file
            owner: root
            group: ssl-cert
            mode: 0640

    - name: check presence of web server certificate incl. chain
      block:

        - name: web server certificate
          ansible.builtin.file:
            path: "{{ idp_webserver_fullchain }}"
            state: file
            owner: root
            group: root
            mode: 0644

- name: vhost configuration
  ansible.builtin.template:
    src: "templates/etc/apache2/sites-available/vhost.conf.j2"
    dest: "/etc/apache2/sites-available/{{ idp_fqdn }}.conf"
    owner: root
    group: root
    mode: 0644

# VHost config is not enabled automatically. Check that you have
# certificate/chain and key in place before proceeding.
#- name: enable the vhost
#  ansible.builtin.command: "a2ensite {{ idp_fqdn }}.conf"
#  args:
#    chdir: /etc/apache2/sites-available
#  register: enable_vhost
#  changed_when: "'already enabled' not in enable_vhost.stdout"
#  notify: restart apache
