---
# GPG is not installed by default on some APT based distributions
- name: ensure that gpg is installed
  ansible.builtin.apt:
    name: gpg
    state: present

- name: install Tomcat MariaDB library
  ansible.builtin.apt:
    name: libmariadb-java
    state: present

- name: create directory for shibboleth downloads
  ansible.builtin.file:
    path: /opt/install
    state: directory
    owner: root
    group: root
    mode: 0755

# Download the Shibboleth version number given in group_vars/idphosts/vars
- name: download the latest shibboleth-idp
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: /opt/install
    force: false
  loop:
    - "{{ idp_archive_url }}"
    - "{{ idp_archive_checksum_url }}"
    - "{{ idp_keys_url }}"

- name: import the PGP key
  ansible.builtin.command: gpg --import PGP_KEYS
  args:
    chdir: /opt/install
  register: import_pgp_keys
  changed_when: "'imported:' in import_pgp_keys.stdout"

- name: verify the download
  ansible.builtin.command: >
    gpg
    --verify
    shibboleth-identity-provider-{{ shibboleth_idp_version }}.tar.gz.asc
    shibboleth-identity-provider-{{ shibboleth_idp_version }}.tar.gz
  args:
    chdir: /opt/install
  register: verified_download
  changed_when: false

- name: extract the archive if verified
  ansible.builtin.unarchive:
    src: "{{
      '/opt/install/shibboleth-identity-provider-' +
      shibboleth_idp_version +
      '.tar.gz'
    }}"
    dest: /opt/install
    remote_src: true
  when: verified_download is succeeded

- name: make sure installation directory exists
  ansible.builtin.file:
    path: /opt/shibboleth-idp
    state: directory
    owner: root
    group: root
    mode: 0755

- name: merge.properties file for non-interactive installation
  ansible.builtin.template:
    src: templates/opt/shibboleth-idp/idp.merge.properties.j2
    dest: "/opt/shibboleth-idp/idp.merge.properties"
    owner: root
    group: root
    mode: 0644

- name: run the shibboleth installer
  ansible.builtin.shell: >
    JAVA_HOME=/usr
    {{ idp_installation_script }}
    {{
      '-Didp.src.dir=' +
      idp_src_dir
    }}
    -Didp.target.dir=/opt/shibboleth-idp
    -Didp.host.name={{ idp_fqdn }}
    -Didp.scope={{ scope }}
    -Didp.keystore.password={{ keystore_password | quote }}
    -Didp.sealer.password={{ sealer_password | quote }}
    -Didp.merge.properties=/opt/shibboleth-idp/idp.merge.properties
    >> {{ idp_ansible_indicator }}
  # Create a hidden file to be idempotent.
  # To force a reinstallation remove this file, too.
  args:
    creates: "{{ idp_ansible_indicator }}"

- name: fix read permissions for tomcat group on conf and credentials
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: tomcat
    mode: 0755
    recurse: true
  loop:
    - /opt/shibboleth-idp/conf
    - /opt/shibboleth-idp/credentials

- name: fix ownership for tomcat user on metadata and logs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: tomcat
    group: tomcat
    recurse: true
  loop:
    - /opt/shibboleth-idp/logs
    - /opt/shibboleth-idp/metadata
