---
### conf/access-control.xml ###
- name: configure IdP with ipv6
  when: idp_ipv6 is defined
  vars:
    allowed_ranges:
      - "127.0.0.1/32"
      - "::1/128"
      - "{{ statuspage_ipv4 }}"
      - "{{ statuspage_ipv6 }}"
      - "{{ statuspage_dfn_ipv4 }}"
      - "{{ statuspage_dfn_ipv6 }}"
  block: &configure_access

    - name: configure access to IdP webservices
      lineinfile:
        path: /opt/shibboleth-idp/conf/access-control.xml
        regexp: "p:allowedRanges"
        line: "{{
           'p:allowedRanges=\"#{ {' +
           (allowed_ranges | join(', ')) +
          '} }\" />'
         }}"
        insertafter: '<bean parent="shibboleth.IPRangeAccessControl"'

    - name: configure access to status page for own and DFN IP ranges
      blockinfile:
        path: /opt/shibboleth-idp/conf/access-control.xml
        block: |
          <entry key="StatusAccessByIPAddress">
              <bean parent="shibboleth.IPRangeAccessControl"
              "{{
                  'p:allowedRanges=\"#{ {' +
                  (allowed_ranges | join(', ')) +
                  '} }\" />'
                }}"
          </entry>
        insertbefore: "</util:map>"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"


- name: configure IdP without ipv6
  when: idp_ipv6 is undefined
  vars:
    allowed_ranges:
      - "127.0.0.1/32"
      - "::1/128"
      - "{{ statuspage_ipv4 }}"
      - "{{ statuspage_dfn_ipv4 }}"
      - "{{ statuspage_dfn_ipv6 }}"
  block: *configure_access

- name: add reference to access policy in idp.properties
  lineinfile:
    path: /opt/shibboleth-idp/conf/idp.properties
    line: idp.status.accessPolicy=StatusAccessByIPAddress
