---
- name: get certificate to validate signed metadata
  ansible.builtin.get_url:
    url: 'https://www.aai.dfn.de/metadata/dfn-aai.pem'
    dest: /etc/ssl/aai/dfn-aai.pem
    owner: root
    group: root
    mode: 0644
    force: true
    # this is the sha256sum of the file, not the openssl fingerprint published on the website
    checksum: sha256:b16a751a845e88c4895934714f0fd9b393c7ea043e0039b59e7e8d1287b7e57a

### metadata/idp-metadata.xml ###
- name: link self signed certificate in idp.properties
  ansible.builtin.lineinfile:
    path: /opt/shibboleth-idp/conf/idp.properties
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - regexp: "^idp.signing.key"
      line: "{{ 'idp.signing.key=' + saml_privatekey['filename'] }}"
    - regexp: "^idp.signing.cert"
      line: "{{ 'idp.signing.cert=' + saml_certificate['filename'] }}"
    - regexp: "^idp.encryption.key"
      line: "{{ 'idp.encryption.key=' + saml_privatekey['filename'] }}"
    - regexp: "^idp.encryption.cert"
      line: "{{ 'idp.encryption.cert=' + saml_certificate['filename'] }}"

# manipulated and hopefully complete idp-metadata.xml
- name: create idp-metadata.xml for DFN-AAI metadata administration tool
  vars:
    samlcert_content: "{{ saml_certificate['certificate'] }}"
  ansible.builtin.template:
    src: templates/opt/shibboleth-idp/metadata/idp-metadata.xml.j2
    dest: /opt/shibboleth-idp/metadata/idp-metadata.xml
    owner: root
    group: root
    mode: 0644

- name: fetch certificate to validate MDQ
  ansible.builtin.get_url:
    url: https://www.aai.dfn.de/fileadmin/metadata/dfn-aai-mdq.pem
    dest: /etc/ssl/aai/dfn-aai-mdq.pem
    # checksum of file on DFN server (not fingerprint on website)
    checksum: "{{ mdq_checksum }}"

- name: add metadata providers
  ansible.builtin.template:
    src: templates/opt/shibboleth-idp/conf/metadata-providers.xml.j2
    dest: /opt/shibboleth-idp/conf/metadata-providers.xml
    owner: root
    group: tomcat
    mode: 0755
