- name: download German language file
  ansible.builtin.get_url:
    url: https://shibboleth.atlassian.net/wiki/download/attachments/1265631751/messages_de.properties
    dest: /opt/shibboleth-idp/messages/messages_de.properties
  notify: rebuild war file
