---
- name: enable the intercept consent module
  block:

    - name: check if the intercept consent module is enabled
      ansible.builtin.command: "bin/module.sh --test idp.intercept.Consent"
      args:
        chdir: /opt/shibboleth-idp
      register: idp_intercept_consent_status
      failed_when: idp_intercept_consent_status.rc != 0

  rescue:

    - name: enable the intercept consent module
      ansible.builtin.command: "bin/module.sh --enable idp.intercept.Consent"
      args:
        chdir: /opt/shibboleth-idp
      register: idp_intercept_consent_enable
      failed_when: "'[FAILED]' in idp_intercept_consent_enable.stdout"

- name: correct file permissions
  ansible.builtin.file:
    path: /opt/shibboleth-idp/conf/intercept/consent-intercept-config.xml
    state: file
    owner: root
    group: tomcat
    mode: 0755

- name: modify consent intercept configuration
  ansible.builtin.blockinfile:
    path: /opt/shibboleth-idp/conf/intercept/consent-intercept-config.xml
    block: |
      <bean id="shibboleth.consent.terms-of-use.Key" class="com.google.common.base.Functions" factory-method="constant">
          <constructor-arg value="my-terms"/>
      </bean>
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    insertbefore: "<!-- Attribute Release configuration -->"

- name: template for relying-party.xml
  ansible.builtin.template:
    src: templates/opt/shibboleth-idp/conf/relying-party.xml.j2
    dest: /opt/shibboleth-idp/conf/relying-party.xml
    owner: root
    group: tomcat
    mode: 0755

- name: Add link to terms of use in footer
  ansible.builtin.copy:
    dest: /opt/shibboleth-idp/edit-webapp/tou.jsp
    content: |
      <%@ page pageEncoding="UTF-8" %>
      <%@ taglib uri="http://www.springframework.org/tags" prefix="spring" %>
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <title>
            <spring:message code="root.title" text="Shibboleth IdP" /> - <spring:message code="my-tou.title" text="Terms of Use" />
          </title>
          <link rel="stylesheet" type="text/css" href="<%= request.getContextPath()%>/css/consent.css">
        </head>
        <body>
          <div class="box">
            <header>
              <a href="<spring:message code="idp.logo.target.url" />" target="_blank">
                <img src="<%= request.getContextPath() %><spring:message code="idp.logo" />"
                alt="<spring:message code="idp.logo.alt-text" text="logo" />">
              </a>
            </header>
            <div id="tou-content">
              <spring:message code="my-tou.text" text="Terms of Use" />
            </div>
            <footer>
              <div class="container container-footer">
                <p class="footer-text">
                  <strong>
                    &copy; <spring:message code="idp.logo.alt-text" /> <spring:message code="idp.url.copyyear" /> |
                    <a title="Impressum" href="<spring:message code="idp.url.imprint" />" target="_blank">
                      Impressum
                    </a>
                  </strong>
                </p>
              </div>
            </footer>
          </div>
        </body>
      </html>
    owner: root
    group: root
    mode: 0644
  notify: rebuild war file
