- name: install mariadb-dependecies
  ansible.builtin.apt:
    name: ['mariadb-client', 'libmariadb-java', 'python3-pymysql']
    state: present

- ansible.builtin.import_tasks: 11-install-database-server.yml
  tags: install-database-server
  when: idp_local_db

- ansible.builtin.import_tasks: 12-use-external-database.yml
  tags: install-database-dependecies
  when: not idp_local_db

- name: create symlink for tomcat
  ansible.builtin.file:
    src: /usr/share/java/mariadb-java-client.jar
    dest: /var/lib/tomcat10/lib/mariadb-java-client.jar
    state: link
  notify: restart tomcat

# JDBC plugin is installed earlier in the process together with other plugins.

- name: configure database access via JDBCStorageService
  ansible.builtin.blockinfile:
    path: /opt/shibboleth-idp/conf/global.xml
    block: |
      <bean id="shibboleth.MySQLDataSource"
          class="%{mysql.class}"
          p:driverClassName="org.mariadb.jdbc.Driver"
          p:url="%{mysql.url}"
          p:username="%{mysql.username}"
          p:password="%{mysql.password}"
          p:maxWait="15000"
          p:testOnBorrow="true"
          p:maxActive="100"
          p:maxIdle="100"
          p:validationQuery="select 1"
          p:validationQueryTimeout="5" />
      <bean id="JDBCStorageService"
          parent="shibboleth.JDBCStorageService"
          p:cleanupInterval="%{idp.storage.cleanupInterval:PT10M}"
          p:dataSource-ref="shibboleth.MySQLDataSource" />
    insertbefore: </beans>
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
  notify: restart tomcat

- name: add database credentials to idp.properties
  ansible.builtin.blockinfile:
    path: /opt/shibboleth-idp/conf/idp.properties
    block: |
      mysql.class    = org.apache.tomcat.jdbc.pool.DataSource
      mysql.url      = jdbc:mysql://{{ database_host }}:3306/{{ database_name }}
      mysql.username = {{ database_user }}
    insertbefore: EOF

- name: add database password to secrets.properties
  ansible.builtin.lineinfile:
    path: /opt/shibboleth-idp/credentials/secrets.properties
    regexp: "^mysql.password"
    line: mysql.password = {{ database_password }}
  no_log: true
