---
- name: add institution branding
  # look for favicon and logo but only try to copy them if they exist
  loop: >
    {{
      query('fileglob', 'files/logo.png') |
      join(
        query('fileglob', 'files/favicon.ico')
      )
    }}
  loop_control:
    loop_var: brand_image
  copy:
    src: "{{ brand_image }}"
    dest: "{{
      '/opt/shibboleth-idp/edit-webapp/images/' +
      (brand_image | basename)
    }}"
    owner: root
    group: root
    mode: 0644
  notify: rebuild war file

- name: add directory htdocs
  file:
    path: /opt/shibboleth-idp/htdocs
    state: directory
    owner: root
    group: root
    mode: 0755

- name: add favicon for IdP
  copy:
    src: files/favicon.ico
    dest: /opt/shibboleth-idp/htdocs/favicon.ico
    owner: root
    group: root
    mode: 0644

- name: create robots.txt, avoid errors from for search engines
  template:
    src: templates/opt/shibboleth-idp/htdocs/robots.txt.j2
    dest: /opt/shibboleth-idp/htdocs/robots.txt
    owner: root
    group: root
    mode: 0644
